In [3]:
import numpy as np


In [5]:
print(np._version_)
np.show_config()

AttributeError: module 'numpy' has no attribute '_version_'

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a= np.zeros(10)


In [22]:
a[4] = 5

In [24]:
print(a)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [28]:
z= np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [32]:
a = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(a)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [34]:
z= np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
nz= np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [46]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
z= np.random.random((3,3,3))
print(z)

[[[0.24436227 0.99827263 0.91028786]
  [0.5001733  0.40424118 0.41694161]
  [0.50316673 0.88513212 0.89427422]]

 [[0.30077574 0.47811086 0.91430642]
  [0.65918987 0.03437867 0.43334985]
  [0.3850184  0.19225034 0.14696688]]

 [[0.86761567 0.71464341 0.67202049]
  [0.13909352 0.49171873 0.37631748]
  [0.8781866  0.02656993 0.49252101]]]


In [64]:
z= np.random.random((10,10))
print(z)

[[0.85875558 0.64254456 0.99685561 0.9362246  0.57884774 0.53533936
  0.10918975 0.61239908 0.13952101 0.07940948]
 [0.10698198 0.46658461 0.38547026 0.18776038 0.36143691 0.98028909
  0.45363097 0.9054699  0.22185656 0.25414252]
 [0.42784616 0.89413021 0.3108893  0.65920727 0.12808083 0.69331873
  0.38513678 0.2523571  0.59816088 0.1195904 ]
 [0.40688193 0.08856047 0.84818879 0.91276126 0.95118048 0.58178764
  0.62258596 0.37563039 0.70373458 0.22841912]
 [0.22444175 0.22637896 0.56494715 0.16609576 0.90745528 0.46345417
  0.99398478 0.05674412 0.33664085 0.21192475]
 [0.85221528 0.3914419  0.76646924 0.68895741 0.23082854 0.77098747
  0.82477875 0.97754131 0.00257019 0.45336216]
 [0.64128229 0.16848152 0.76460957 0.2333894  0.47630772 0.28537518
  0.76991258 0.25841524 0.74065118 0.16980119]
 [0.7649229  0.28513869 0.04175943 0.97438117 0.38634182 0.17471283
  0.96530987 0.19641076 0.95276929 0.40869233]
 [0.86715835 0.03894103 0.1884785  0.29264224 0.75568142 0.66416297
  0.90216143

In [66]:
zmax, zmin= z.max(), z.min()
print(zmax, zmin)

0.9968556101915634 0.002570194807303694


In [68]:
z= np.random.random((30))
mean = z.mean()
print(mean)

0.4847700945067082


In [72]:
z = np.ones((10,10))
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [88]:
z[1:9, 1:9]= 0

In [90]:
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [104]:
0.3 == 3*0.1

False

In [108]:
v1 = np.array([1,2,3,4,5])
v2= np.array([1,2,3,4,5])
g= np.vstack
print(g)

<function vstack at 0x000001EC142B7420>


In [128]:
g= np.diag(1+np.arange(4), k= -1)

In [130]:
print(g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [170]:
z= np.zeros((8,8), dtype= int)
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [176]:
print(z)

[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]


In [196]:
z= np.zeros((8,8), dtype= int)
z[1::2, ::2]=1 
z[::2, 1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
create a checkboard using tile function

In [220]:
z= np.tile(np.array([[0,1],[1,0]]), (3,3))

In [222]:
print(z)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [236]:
# Normalize 5*5 random matrix
z=np.random.random([5,5])
z= (z-z.max())/(zmax-z.min())
print(z)



[[-0.4896303  -1.11565033 -0.19622016 -0.81645571 -0.17953251]
 [-1.06464363 -0.46464042 -0.20075848 -0.42845989 -0.75696228]
 [-0.06598661 -0.28814    -0.95544875 -0.50149353 -0.18884549]
 [-0.75253317 -0.90787357 -0.78014895 -0.77223112 -0.83351233]
 [-0.3983318   0.         -0.21332255 -0.11684179 -1.10922714]]


In [15]:
# Create the custom datatype that describe a colur as four unisigned byte
colour = np.datatype([("r", np.ubyte,1),
                      ("r", np.ubyte,1),
                      ("r", np.ubyte,1),
                      ("r", np.ubyte,1)])

AttributeError: module 'numpy' has no attribute 'datatype'

In [11]:
import numpy as np

# Define a NumPy array
arr = np.array([1, 2, 3, 4])

# Check the data type of the array
print(arr.dtype)  # Output: int64 (or another type depending on your system)

# Create a NumPy array with a specific data type
arr_float = np.array([1, 2, 3, 4], dtype=np.float32)
print(arr_float.dtype)  # Output: float32


int32
float32


In [19]:
import numpy as np

# Define a custom data type for color with 4 unsigned bytes (r, g, b, a)
colour = np.dtype([("r", np.ubyte),  # Red channel
                  ("g", np.ubyte),  # Green channel
                  ("b", np.ubyte),  # Blue channel
                  ("a", np.ubyte)]) # Alpha channel

# Now you can create an array of that custom datatype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=colour)

print(color_array)
print(color_array[0])  # Accessing the first color


[(255,   0, 0, 255) (  0, 255, 0, 255)]
(255, 0, 0, 255)


In [27]:
a = np.ones((5,3))
b= np.ones((3,2))
z= np.dot(a,b)
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [39]:
#negate all the element which are between 3 and 8
z= np.arange(11)
z[(z>3)& (z<=8)] *= -1
print(z)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [58]:
print(sum(range(5), -1))



10


In [52]:
from numpy import*
print(sum(range(5),-1))

10
