In [5]:
import numpy as np


In [7]:
a = np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [13]:
b = np.array([[2.3,4.3,3.3],[23,43,2.3]])
print(b)

[[ 2.3  4.3  3.3]
 [23.  43.   2.3]]


In [ ]:
#getting dimension

In [17]:
b.ndim


2

In [ ]:
#getting shape

In [19]:
b.shape

(2, 3)

In [21]:
a.shape

(4,)

In [23]:
#get type
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('float64')

In [27]:
a.itemsize

4

In [29]:
b.size

6

In [31]:
a.nbytes


16

In [33]:
b.nbytes

48

In [48]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#Accessing/changing specific element, row, column, etc


In [50]:
#Get a specific element
a[0,-2]

6

In [52]:
#Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [54]:
a[:, 3]

array([ 4, 11])

In [62]:
#More advanced [Startindex:endindex:stepsize
a[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [64]:
a[1,6] = 762
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12  13 762]]


In [92]:
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [78]:
#Getting specific item from 3d array
b[1,1,0]

7

In [80]:
b[1,1,:]

array([7, 8])

In [82]:
b[0,:,0]

array([1, 3])

In [98]:
#Replacing in 3d 
b[1,1,:]= [13,18]

In [100]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [13, 18]]])

**IniTALIZATING THE DIFFERENT TYPE OF ARRAY**

In [111]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.full((2,2), 99, dtype= 'float32')


array([[99., 99.],
       [99., 99.]], dtype=float32)

In [123]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [133]:
np.random.rand(2,4)

array([[0.51377588, 0.36850639, 0.37998214, 0.87222675],
       [0.52662517, 0.01115063, 0.67056274, 0.5858414 ]])

In [146]:
#Random interger value
np.random.randint(4,7, size= (3,4))

array([[5, 6, 4, 4],
       [4, 4, 5, 4],
       [5, 4, 4, 4]])

In [150]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [170]:
arr =np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print(r1)


              


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [184]:
a = np.array([1,2,30])
b=a.copy()
print(b)
b[1]= 100
print(b)

[ 1  2 30]
[  1 100  30]


In [186]:
#linear algebra
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [190]:

b= np.full((3,3),2)
print(b)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [208]:
a= np.full((2,3),4)
print(a)
b= np.full((3,4),3)
print(b)
np.matmul(a,b)

[[4 4 4]
 [4 4 4]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[36, 36, 36, 36],
       [36, 36, 36, 36]])

In [220]:
c= np.identity(4)
print(c)
np.linalg.det(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


1.0

#statistics#

In [224]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
np.min(stats)

1

In [228]:
np.max(stats)

6

In [232]:
np.min(stats)

1

In [234]:
np.sum(stats)

21

In [236]:
np.sum(stats, axis= 0)

array([5, 7, 9])

In [238]:
#reorganizing array

In [13]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [7]:


# Create a 2D NumPy array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Print the array
print(a)


[[1 2 3 4]
 [5 6 7 8]]


In [21]:
after= before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [29]:
h1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

In [ ]:
# Load data from file
np.genfromtxt('filename', delimiter= ',')


### Boolen  masking and advanced indexing###

In [ ]:
filedata[filedata>50]f